
name: Resume CI Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ github.run_number }}

      - name: Build latest
        run: docker build . --file Dockerfile --tag my-image-name

      - name: Login to Docker hub
        run: docker login -u ${{ secrets.REGIS_U }} -p ${{ secrets.REGIS_P }}

      - name: Tag image
        run: docker tag my-image-name:${{ github.run_number }} ${{ secrets.REGIS_U }}/my-image-name:${{ github.run_number }}

      - name: Push image
        run: docker push ${{ secrets.REGIS_U }}/my-image-name:${{ github.run_number }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3.91.170.238
          username: ec2-username
          key: ${{ secrets.KEY }}
          script: |
              docker stop resume || echo ""
              docker rm resume || echo ""
              docker run -d --name resume -p 8080:5001 ${{ secrets.REGIS_U }}/my-image-name:${{ github.run_number }}
  
  
  
  
  
  
























